# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://everjaydesigns.com"
baseurl: ""

# Google tracking id
google-tracking-id: "false"

#############
# HTML Head #
#############

lang: "en"
author: "EverJay Designs"
title: "EverJay Designs"
description: "Design portfolio for EverJay Designs."
keywords: "everjay, graphic design, portfolio, design portfolio, ej zamloot, everett zamloot, art, everjay designs"
favicon: ""
################
# Header layout#
################
black-favicon: ""
background-img: "https://res.cloudinary.com/teasfbaz/image/upload/f_auto,q_auto/Chalk-Noodles-BG"

##############################
# Dynamic Text on the Header #
##############################

quote: "Hi, I'm EJ! Let's make something beautiful."
me-img: "https://res.cloudinary.com/teasfbaz/image/upload/v1787955984/my-face.jpg"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"




################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "https://res.cloudinary.com/teasfbaz/image/upload/v1787955984/my-face.jpg"
author_blurb: "Author blurb goes here."

##################
# Social Buttons #
##################

social:
  - icon: "tumblr"
    url: "https://www.tumblr.com/everjay-art"
  - icon: "instagram"
    url: "https://www.instagram.com/everjay.art"
  - icon: "facebook"
    url: "https://www.facebook.com/everjaydesigns"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Contact: "contact"

syntax_theme: everforest

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
